logging:
  level:
    ROOT: WARN
    org.springframework: DEBUG
    io.spring.start: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

server:
  port: 8181
  error:
    include-message: always
  forward-headers-strategy: native

spring:
  config:
    import: initializer-metadata.yml
  jackson:
    serialization:
      write-dates-as-timestamps: false
  task:
    execution:
      thread-name-prefix: initializr-
  web:
    resources:
      cache:
        use-last-modified: false
starter-config:
  fetch-boot-version: true
  spring-boot-metadata-url: https://spring.io/project_metadata/spring-boot
