logging:
  level:
    org.springframework.core.env: warn
    org.springframework.jndi: warn
    io.spring.start: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

server:
  port: 8181
  error:
    include-message: always
  forward-headers-strategy: native

spring:
  config:
    import: application-initializer.yml
  jackson:
    serialization:
      write-dates-as-timestamps: false
  task:
    execution:
      thread-name-prefix: initializr-
  web:
    resources:
      cache:
        use-last-modified: false

